services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env.prod
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: 'postgres:15.5'
    ports:
      - 5432:5432
    env_file: ./.env.prod
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      ENV: dev
    networks:
      - backend

  localstack:
    image: localstack/localstack
    ports:
      - 127.0.0.1:4566:4566
      - 127.0.0.1:4510-4559:4510-4559
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/localstack-setup.sh
    networks:
      - backend

networks:
  backend:

volumes:
  postgres:
  localstack:
